services:
  api:
    image: on-service-api:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ../app:/app
      - ../configuration:/configuration
    tty: True
    ports:
      - 9090:9090