services:
  api:
    image: on-service-api:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: test
    volumes:
      - ../app:/app
    tty: True
    command: ["poetry", "run","pytest", "-v", "/app/test/"]
